# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ["src/launcher.py"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "PyQt5.QtWebEngineCore",
        "PyQt5.QtWebEngineWidgets",
        "PyQt5.QtWebChannel",
        "PyQt5.QtBluetooth",
        "PyQt5.QtNfc",
        "PyQt5.QtSerialPort",
        "PyQt5.QtSensors",
        "PyQt5.QtPositioning",
        "PyQt5.QtMultimedia",
        "PyQt5.QtMultimediaWidgets",
        "PyQt5.QtTextToSpeech",
        "PyQt5.QtAudioEngine",
        "PyQt5.Qt3DCore",
        "PyQt5.Qt3DExtras",
        "PyQt5.Qt3DInput",
        "PyQt5.Qt3DRender",
        "PyQt5.QtDataVisualization",
        "PyQt5.QtChart",
        "PyQt5.QtGraphicalEffects",
        "PyQt5.QtQuick",
        "PyQt5.QtQml",
        "PyQt5.QtQuickWidgets",
        "PyQt5.QtQuickParticles",
        "PyQt5.QtSql",
        "PyQt5.QtNetworkAuth",
        "PyQt5.QtRemoteObjects",
        "PyQt5.QtHelp",
        "PyQt5.QtDesigner",
        "PyQt5.QAxContainer",
        "PyQt5.QtTest",
        "PyQt5.QtPrintSupport",
        "PyQt5.QtWidgets",
        "PyQt5.QtGui",
        "difflib",
        "pickle",
        "heapq",
        "inspect",
        "pydoc",
        "doctest",
        "unittest",
        "test",
        "tests",
    ],
    noarchive=True,
    optimize=2,
)
pyz = PYZ(a.pure, level=0)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="ParVuExLauncher",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="ParVuExLauncher",
)
