# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ["src/main.py"],
    pathex=["src"],
    binaries=[],
    datas=[
        ("src/schemas.py", "."),
        ("src/query_revisor.py", "."),
        ("src/utils.py", "."),
        ("src/core.py", "."),
        ("src/gui_tools.py", "."),
        ("src/app.py", "."),
        ("src/components.py", "."),
        ("src/static/loading-thinking.gif", "./static/"),
        ("src/static/logo.jpg", "./static/"),
        ("src/static/help.md", "./static/"),
        ("src/settings/settings.json", "./settings/"),
        ("src/settings/default_settings.json", "./settings/"),
        ("src/history/recents.json", "./history/"),
    ],
    hiddenimports=[
        "pydantic",
        "loguru",
        "duckdb",
        "pandas",
        "chardet",
        "com_menu",
        "com_results",
        "com_sql_edit",
        "com_dialog",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "PySide6",
        "PySide6.*",
        "PyQt5.QtWebEngineCore",
        "PyQt5.QtWebEngineWidgets",
        "PyQt5.QtWebChannel",
        "PyQt5.QtBluetooth",
        "PyQt5.QtNfc",
        "PyQt5.QtSerialPort",
        "PyQt5.QtSensors",
        "PyQt5.QtPositioning",
        "PyQt5.QtMultimedia",
        "PyQt5.QtMultimediaWidgets",
        "PyQt5.QtTextToSpeech",
        "PyQt5.QtAudioEngine",
        "PyQt5.Qt3DCore",
        "PyQt5.Qt3DExtras",
        "PyQt5.Qt3DInput",
        "PyQt5.Qt3DRender",
        "PyQt5.QtDataVisualization",
        "PyQt5.QtChart",
        "PyQt5.QtGraphicalEffects",
        "PyQt5.QtQuick",
        "PyQt5.QtQml",
        "PyQt5.QtQuickWidgets",
        "PyQt5.QtQuickParticles",
        "PyQt5.QtSql",
        "PyQt5.QtNetworkAuth",
        "PyQt5.QtRemoteObjects",
        "PyQt5.QtHelp",
        "PyQt5.QtDesigner",
        "PyQt5.QAxContainer",
        "PyQt5.QtTest",
        "PyQt5.QtPrintSupport",
        "pandas.tests",
        "pandas.io.tests",
        "numpy.tests",
        "numpy.f2py",
        "numpy.distutils",
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure, level=0)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    exclude_binaries=False,
    name="ParVuEx",
    debug=False,
    icon="src/static/logo.ico",
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
